name: 'Custom ENV vars'

on:
  workflow_dispatch:

env:
  DAY_OF_WEEK: Munday
  testvar: value-1

jobs:
  mainjob:
    name: 'print the env vars'
    runs-on: ubuntu-latest

    env:
      Greetings: Dear
      testvar: value-2
    
    steps:
    - name: print-values-of-env-vars
      run:
        echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        echo "testvar $testvar"
        echo "testvar ${{env.testvar}}"
      env:
        First_Name: student
        testvar: value-3
